name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch: # Allows manual trigger if needed

jobs:
  deploy-infra:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-2

      - name: Terraform Init
        run: |
          cd terraform
          echo "AWS region: ap-south-2"
          aws sts get-caller-identity
          terraform init -reconfigure -input=false -no-color

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -var-file="dev.tfvars"

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -var-file="dev.tfvars" --auto-approve

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -var-file="dev.tfvars" --auto-approve